spring:
  application:
    name: blocker
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/bankapp
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/bankapp
        registration:
          bankapp:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: bankapp
            client-secret: UB2e3I2LfwQZyIuWHkmtJ01v0BajybBW
            scope: profile
            clientAuthenticationMethod: client_secret_post # Способ передачи секрета
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint:  http://127.0.0.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1