server:
  port: 8080
spring:
  application:
    name: front
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/bankapp
        registration:
          bankapp:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: bankapp
            client-secret: UB2e3I2LfwQZyIuWHkmtJ01v0BajybBW
            scope: profile
            clientAuthenticationMethod: client_secret_post # Способ передачи секрета
feign:
  accounts: http://localhost:8081
  exchange: http://localhost:8084
  cash: http://localhost:8083
  transfer: http://localhost:8087
  notifications: http://localhost:8086

frontend:
  rates:
    url: http://localhost:8080/api/rates
  notifications:
    url: http://localhost:8080/api/notifications

management:
  zipkin:
    tracing:
      endpoint:  http://127.0.0.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1