spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8088
  profiles:
    active: default
  cloud:
    config:
      label: main
circuit-breaker:
  timeout-seconds: 5