apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "front-service.fullname" . }}
  labels:
    {{- include "front-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "front-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "front-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "front-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }} # Use the service port value from values.yaml
              protocol: TCP
          livenessProbe: # Example for Spring Boot Actuator
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 60
          readinessProbe: # Example for Spring Boot Actuator
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
              value: "http://myapp-keycloak-service.default.svc.cluster.local:8080/realms/bankapp"
            - name: FEIGN_ACCOUNTS
              value: "http://myapp-accounts-service.default.svc.cluster.local:8080"
            - name: FEIGN_EXCHANGE
              value: "http://myapp-exchange-service.default.svc.cluster.local:8080"
            - name: FEIGN_CASH
              value: "http://myapp-cash-service.default.svc.cluster.local:8080"
            - name: FEIGN_TRANSFER
              value: "http://myapp-transfer-service.default.svc.cluster.local:8080"
            - name: FEIGN_NOTIFICATIONS
              value: "http://myapp-notifications-service.default.svc.cluster.local:8080"
            - name: SERVER_PORT
              value: "8080"
            - name: FRONTEND_RATES_URL
              value: "http://front-service.bankapp.local/api/rates"
            - name: FRONTEND_NOTIFICATIONS_URL
              value: "http://front-service.bankapp.local/api/notifications"
          envFrom:
            - configMapRef:
                name: {{ include "front-service.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 