apiVersion: v2
name: bank-app
description: Umbrella chart for Customer and Order microservices
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: front-service
    version: "0.1.0"
    repository: "file://./charts/front-service" # Local path reference
  - name: keycloak-service
    version: "0.1.0"
    repository: "file://./charts/keycloak-service" # Local path reference
