apiVersion: v2
name: bank-app
description: Umbrella chart for Customer and Order microservices
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: front-service
    version: "0.1.0"
    repository: "file://./charts/front-service" # Local path reference
  - name: blocker-service
    version: "0.1.0"
    repository: "file://./charts/blocker-service" # Local path reference
  - name: cash-service
    version: "0.1.0"
    repository: "file://./charts/cash-service" # Local path reference
  - name: exchange-generator-service
    version: "0.1.0"
    repository: "file://./charts/exchange-generator-service" # Local path reference
  - name: transfer-service
    version: "0.1.0"
    repository: "file://./charts/transfer-service" # Local path reference
  - name: accounts-service
    version: "0.1.0"
    repository: "file://./charts/accounts-service" # Local path reference
  - name: exchange-service
    version: "0.1.0"
    repository: "file://./charts/exchange-service" # Local path reference
  - name: notifications-service
    version: "0.1.0"
    repository: "file://./charts/notifications-service" # Local path reference
  - name: keycloak-service
    version: "0.1.0"
    repository: "file://./charts/keycloak-service" # Local path reference
  - name: postgresql
    version: "14.2.3" # Using a specific known stable version from Bitnami history
    repository: "https://charts.bitnami.com/bitnami"
    alias: app-db # Alias to distinguish this instance
  - name: kafka
    version: "19.3.3"  # Use a known stable version from Bitnami (check their version history)
    repository: "https://charts.bitnami.com/bitnami"
    alias: app-kafka
  - name: zipkin
    version: "0.5.0"
    repository: "https://charts.bitnami.com/bitnami"
    alias: app-zipkin
  - name: prometheus
    version: "18.1.1"
    repository: "https://charts.bitnami.com/bitnami"
    alias: app-prometheus
  - name: grafana
    version: "8.2.0"
    repository: "https://charts.bitnami.com/bitnami"
    alias: app-grafana
  - name: elasticsearch
    version: "20.1.2"
    repository: "https://charts.bitnami.com/bitnami"
    alias: app-elastic
  - name: logstash
    version: "6.2.0"
    repository: "https://charts.bitnami.com/bitnami"
    alias: app-logstash
  - name: kibana
    version: "12.1.0"
    repository: "https://charts.bitnami.com/bitnami"
    alias: app-kibana
