server:
  port: 8085
spring:
  application:
    name: exchange-generator
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/bankapp
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/bankapp
        registration:
          bankapp:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: bankapp
            client-secret: UB2e3I2LfwQZyIuWHkmtJ01v0BajybBW
            scope: profile
            clientAuthenticationMethod: client_secret_post # Способ передачи секрета
feign:
  exchange: http://localhost:8084
kafka:
  bootstrap:
    servers: localhost:9092